<?php
namespace Mouf\Doctrine\ORM;

use Doctrine\ORM\Mapping\ClassMetadata;

use Doctrine\ORM\Tools\SchemaTool;

use Doctrine\DBAL\Connection;
use Doctrine\ORM\Configuration;
use Doctrine\Common\EventManager;
use Doctrine\ORM\ORMException;

/**
 * This is a very simple wrapper around Doctrine's EntityManager that exposes its contructor as "public".
 * This allows calling the constructor directly using Mouf.
 *
 * @author David Négrier <david@mouf-php.com>
 * @ExtendedAction {"name":"Generate DBSchema", "url":"entityManagerInstall/", "default":false}
 */
class EntityManager extends \Doctrine\ORM\EntityManager
{

	private $sourceDirectory;
	private $entitiesNamespace;
	private $proxyNamespace;
	private $daoNamespace;

	/**
	 * Creates a new EntityManager that operates on the given database connection
	 * and uses the given Configuration and EventManager implementations.
	 *
	 * @param \Doctrine\DBAL\Connection     $conn
	 * @param \Doctrine\ORM\Configuration   $config
	 * @param \Doctrine\Common\EventManager $eventManager
	 */
	public function __construct(Connection $conn, Configuration $config, EventManager $eventManager)
	{
		// Those security checks are usually performed in EntityManager::create
		if ( ! $config->getMetadataDriverImpl()) {
			throw ORMException::missingMappingDriverImpl();
		}
		if ($eventManager !== null && $conn->getEventManager() !== $eventManager) {
			throw ORMException::mismatchedEventManager();
		}
		 
		parent::__construct($conn, $config, $eventManager);
	}

	public function generateSchemaFromEntities(){
		$metadata = $this->getMetadataFactory()->getAllMetadata();
		if ( ! empty($metadata)) {
			$tool = new SchemaTool($this);
			$tool->dropSchema($metadata);
			$tool->createSchema($metadata);
		}
	}

	public function generateDAOs(){
		//Get Bean / Table list
		$metadata = $this->getMetadataFactory()->getAllMetadata();
		 
		//Get Path where to generate dao files
		$daoPath = ROOT_PATH . $this->sourceDirectory . str_replace("\\", "/", $this->daoNamespace);
		if (!is_dir($daoPath)){
			$oldUmask = umask();
			umask(0);
			$dirCreate = mkdir($daoPath, 0775, true);
			umask($oldUmask);
		}
		
		$daos = array();
		foreach ($metadata as $data){
			list($fullClassName, $className) = $this->generateDAO($data, $daoPath);
			$daos[$fullClassName] = $className;
		}
		
		return  $daos;
	}

	private function generateDAO($data, $daoPath){
		/* @var $data ClassMetaData */
		$entityClass = $data->name;
		$entityName = str_replace($this->entitiesNamespace . "\\", "", $data->name);
		$tableName = $data->table['name'];
		$daoClassName =  $entityName. "Dao";
		$daoBaseClassName =  $entityName. "BaseDao";
		
		//generate magic _call functions : findOne & find By field
		$magicCallsStr = "";
		foreach($data->fieldNames as $fieldName){
			if (array_search($fieldName, $data->identifier) === false){
				$field = \Doctrine\Common\Util\Inflector::classify($fieldName);
				$magicCallsStr .= "
	public function _findBy$field(\$fieldValue, \$orderBy, \$limit, \$offset) {
		return \$this->findBy$field(\$fieldValue, \$orderBy, \$limit, \$offset);
	}
				
	public function _findOneBy$field(\$fieldValue, \$orderBy) {
		return \$this->findOneBy$field(\$fieldValue, \$orderBy);
	}";
			}
		}
		
		$str = "<?php
/*
* This file has been automatically generated by Mouf/ORM.
* DO NOT edit this file, as it might be overwritten.
* If you need to perform changes, edit the $daoClassName class instead!
*/
namespace $this->daoNamespace;

use Mouf\\Database\\DAOInterface;
use Mouf\\Doctrine\\ORM\\EntityManager;
use Doctrine\\ORM\\EntityRepository;

/**
* The $daoBaseClassName class will maintain the persistance of $entityName class into the $tableName table.
*
*/
class $daoBaseClassName extends EntityRepository implements DAOInterface {

	/**
	 * @param EntityManager \$entityManager
	 */
	public function __construct(\$entityManager){
		parent::__construct(\$entityManager, \$entityManager->getClassMetadata('$entityClass'));
	}
	
	/**
	 * Get a bean by it's Id
	 * @param mixed \$id
	 * @return mixed the bean object
	 */
	public function getById(\$id){
		return \$this->find(\$id);
	}
	
	/**
	 * 
	 * Peforms saving on a bean object
	 * @param mixed bean object
	 */
	public function save(\$entity){
		\$this->getEntityManager()->persist(\$entity);
	}
	
	/**
	 * Returns the lis of beans
	 * @return array<mixed> array of bean objects
	 */
	public function getList(){
		return \$this->findAll();
	}
	
	$magicCallsStr
}";
		$fileName = $daoBaseClassName . ".php";
		file_put_contents($daoPath . "/" . $fileName, $str);
		chmod($daoPath . "/" . $fileName, 0664);
		
		$str = "<?php
/*
*/
namespace $this->daoNamespace;

use Mouf\\Database\\DAOInterface;
use Mouf\\Doctrine\\ORM\\EntityManager;
use Doctrine\\ORM\\EntityRepository;

/**
* The $daoClassName class will maintain the persistance of $entityName class into the $tableName table.
*
*/
class $daoClassName extends $daoBaseClassName {
	
	/*** PUT YOUR SPECIFIC QUERIES HERE !! ***/

}";
		$fileName = $daoClassName . ".php";
		file_put_contents($daoPath . "/" . $fileName, $str);
		chmod($daoPath . "/" . $fileName, 0664);
		
		return array($this->daoNamespace . "\\" . $daoClassName , $daoClassName);
	}

	public function setSourceDirectory($sourceDirectory){
		$this->sourceDirectory = $sourceDirectory;
	}
	public function setEntitiesNamespace($entitiesNamespace){
		$this->entitiesNamespace = $entitiesNamespace;
	}
	public function setProxyNamespace($proxyNamespace){
		$this->proxyNamespace = $proxyNamespace;
	}
	public function setDaoNamespace($daoNamespace){
		$this->daoNamespace = $daoNamespace;
	}
}
